testtestdocker:
  build: . 
  container_name: testtestdocker 
  environment:
   - CONTNAME=testtestdocker
  volumes:
   - ./tests/:/tests/:ro
   - .:/docker-file/:ro
   - /var/run/docker.sock:/var/run/docker.sock
lintdocker:
  image: projectatomic/dockerfile-lint
  volumes:
   - .:/root/:ro
  command:
   dockerfile_lint -f Dockerfile
